### PR TITLE
Forecast new data with nnetar model

### PR DESCRIPTION
**Pull request by gabrielcaceres**
How about something like this to address #85?

I essentially wrapped
```
fit <- function(x)
fit2 <- function(x2, model=fit)
forecast(fit2)
```
inside of the `forecast` method to make it easier/quicker to do. 

If it seems like a decent solution, we can modify the other `forecast` methods along similar lines.

Some sample code:
```
fit <- nnetar(lynx)
fit2 <- nnetar(window(lynx,end=1920), model=fit)
fcast <- forecast(fit2,h=14)
fcast
par(mfrow=c(1, 2))
plot(fcast)
lines(lynx)
##
fcast2 <- forecast(fit, h=14, newx=window(lynx,end=1920))
fcast2
plot(fcast)
lines(lynx)
##
## Including xreg
library(fpp)
fit <- nnetar(usconsumption[, 1], xreg=usconsumption[, 2], p=5)
fit2 <- nnetar(window(usconsumption[, 1], end=2006+3/4),
               xreg=window(usconsumption[, 2], end=2006+3/4), model=fit)
fcast <- forecast(fit2,h=12, xreg=window(usconsumption[, 2], start=2007))
fcast
par(mfrow=c(1, 2))
plot(fcast)
lines(usconsumption[, 1])
##
fcast2 <- forecast(fit, h=12, newx=window(usconsumption[, 1], end=2006+3/4),
                   xreg=usconsumption[, 2])
fcast2
plot(fcast)
lines(usconsumption[, 1])
```

### CODE REVIEW

**Comment by robjhyndman** [comment]
This is not what I had in mind with #85. Currently fitted(object) returns in-sample one-step forecasts for the whole length of the series. I plan to add something like fitted(object, h=2) which will return in-sample two-step forecasts for the whole length of the series. Similarly for other values of h. h=1 would remain the default. This will take quite a lot of rewriting, and so it is not going to happen any time soon.

**Comment by gabrielcaceres** [comment]
Oh, I guess I went off of the stackoverflow link in #85, where they were asking about counter-factual forecasts after having fitted a model with the full dataset.

Two questions:
- Do you think this wouldn't be useful to address that type of situation, even if it doesn't address #85?
- Then, by in-sample forecasts, do you mean directly training the model for h-step forecasts instead of the current way of training for one-step and then iteratively predicting?

**Comment by robjhyndman** [comment]
1. I think we mean the same thing, but I'm looking for a more general solution that involves re-writing fitted.xxx functions to allow the model to be re-used iteratively for h>1. There is no need to modify forecast.xxx functions to do this.

2. No, I mean using the same model that has been fitted to the whole data set, and using it to produce forecasts based on subsets of the data, as described in the SO link.

**Comment by gabrielcaceres** [comment]
Ok, yeah I see what you mean.

My reasoning for implementing it as such and modifying forecast.xxx was twofold:
1. It makes use of the forecast.xxx machinery to create h-step forecasts without re-writing the fitting functions internally.
2. It adds the flexibility of accepting as input either a subset of the original data (like the examples in my first post) or some other arbitrary data.

My initial intuition to accomplish the h-step in-sample forecasts for the *full* series, would have been to then wrap 'forecast()' inside a generic function that simply loops over the subsets of the original series and creates the h-step forecasts at each point.

Now I'll grant that this way there's some redundant computation in re-assigning the model parameters to all the subsets of the series as they are forecasted. Also, the code also isn't as clean as it could be.

But the upside that it can be accomplished with a handful of extra lines in the forecast.xxx methods (which already exist for each model) plus one single general function to loop over and forecast subsets of the original series, instead of extensively re-writing a fitted.xxx method for each model type. 

Now, I completely understand that you may prefer the cleaner and more efficient approach of writing the functionality directly into dedicated methods rather than bootstrapping the available pieces together as I described.

**Comment by robjhyndman** [comment]
This is roughly what I had in mind:

```
library(forecast)
fitted.ets <- function(object, h=1, ...)
{
  if(h==1)
    return(object$fitted)

  x <- getResponse(object)
  tspx <- tsp(x)
  fits <- object$fitted*NA
  n <- length(fits)
  for(i in 1:(n-h))
  {
    newx <- ts(x[1:i], start=tspx[1], frequency=tspx[3])
    refit <- try(ets(newx, model=object), silent=TRUE)
    if(!is.element("try-error", class(refit)))
      fits[i+h] <- forecast(refit, h=h)$mean[h]
  }
  return(fits)
}

mod <- ets(WWWusage)
plot(WWWusage)
lines(fitted(mod, h=1), col='red')
lines(fitted(mod, h=2), col='green')
lines(fitted(mod, h=3), col='blue')
legend("topleft", legend=paste("h =",1:3), col=2:4, lty=1)
```

That doesn't quite work properly for the first few observations, but otherwise is ok. The plan is to write something like this for all the classes that have a forecast.xxx method.

**Comment by gabrielcaceres** [comment]
Ok, yeah. That's actually very similar to what I meant, just packaged a bit different.

A couple questions:

Generally speaking, is there much more you'd want to add to your sample code? Because implementing that for the other classes should be pretty straightforward, either editing it slightly for each method or changing the fitting to a 'do.call' to use one function for all classes.

The main thing I could see varying between the different classes is how the first few points are handled (if at all). And possibly NAs depending on how the 'model' argument is implemented for each class (ok and some extras like 'xreg').

Also, would you be interested in being able to apply this to new data to do *out-of-sample* h-step forecasts? Say, having the default be in-sample but with an optional 'newx' argument.
If so, do you think it should be in a brand new function instead of either 'fitted' or 'forecast'? 

If you feel this is the type of thing that ends up being more work to have to explain your vision for the package and prefer to just implement it yourself when you have the time, just let me know and I'll leave it as is!

**Comment by gabrielcaceres** [comment]
I just realized that my last question regarding new data is not all that useful...
One can simply do:
```
newfit <- function(x, model = oldfit)
hstep <- fitted(newfit, h=3)
```

**Pull request closed without merging**
