### PR TITLE
Add travis-CI and coveralls support

### PR DESCRIPTION
**Pull request by zachmayer**

### CODE REVIEW

**Comment by zachmayer** [comment]
This adds automated unit testing via [travis](https://travis-ci.org), and unit test coverage reporting via [coveralls](https://coveralls.io/).

This is nice because travis will automatically run R CMD CHECK on every commit you make to github, as well as on Pull Requests contributors submit to you.  Furthermore, coveralls will identify blind spots in unit test coverage.

If these sounds good to you, you'll need to make an account on travis and coveralls, and then enable them on the robjhyndman/forecast repository.

**Comment by zachmayer** [comment]
You can take a look at my fork to see what the badges will look like:
https://github.com/zachmayer/forecast/tree/3c0c77e23f6a7a752ece848b39e2909c074c3c67

**Comment by robjhyndman** [comment]
Thanks Zach. I've pulled the merge. I suspect I have to do some other edits as it is not triggering yet. Any idea?

**Comment by zachmayer** [comment]
The next commit to the github repo should trigger a travis build and coveralls check.  You can just check in a dummy commit.

**Pull request merged**
