### PR TITLE
forecast.nnetar prediction intervals

### PR DESCRIPTION
**Pull request by gabrielcaceres**
Apologies this ran a bit long...

This is a first step towards getting good prediction intervals for `nnetar` (#241). It creates PIs by creating future sample paths to estimate the variability in the data, but ignoring model uncertainty.

- Wrote a `simulate.nnetar` function to create sample future paths. 
    * Works by iteratively forecasting single steps and then adding a noise component (either bootstrapped residuals or normally distributed). 
    * Since it uses `forecast.nnetar` for calculations, it repeatedly re-applies the model as it extends the dataset, which isn't very efficient. This can be avoided by including significant parts of the `forecast.nnetar` internals, but that'd be more time consuming to make it fully functional. Might look into doing it in the future.
- Included option to calculate PIs in `forecast.nnetar`
   * It is *slow* (see sample code below for example). It can probably be sped up by the `simulate.nnetar` improvements described above, but not sure how significant the difference will be. 
   * One concern is that the residuals (used for new innovations, either directly by bootstrapping or indirectly through their standard deviation), can be misleadingly small. If a network is too large, it's easy for it to overfit and have arbitrarily small residuals, and thus the PIs to not be very meaningful or useful.
   * See sample code below and attached plots for an example where the automatically selected number of lags and corresponding size of the network are way too big given the amount of data. Note that the first plot *does* in fact have PIs, but are just too small to be seen. Contrast with the next two plots which use a smaller network, and the same large original network but with regularization, respectively.
   * The concerns above should be ameliorated once we have functions to do cross-validation/bootstrapping of the fits. In addition to helping us quantify model uncertainty, we can also use the CV residuals instead of the fitted residuals for PIs.
   * I included a `PI` flag (like `forecast.ets`) which defaults to `FALSE` so it's not unexpectedly time consuming to forecast.

Some questions:

- Regarding documentation (which I haven't modified yet), since the functionality of `nnetar` and `forecast.nnetar` has grown a good bit, would it be appropriate to split the help page into separate entries (like the other `forecast` methods)?
- Do you want `simulate.nnetar` to be exported and user accessible?
- Thoughts about what the default `npaths` should be for `forecast.nnetar`, considering how long the calculation takes?
- Not directly related to this PR, but I noticed that the sigma^2 calculation in the `print` method uses the mean of the squared residuals. Since the residuals might not sum to zero, should we include that term? (shouldn't be a huge difference, but figured while we're at it...).

Here's some sample code. Note the issue with the residuals, and the speed.
```

library(fpp)
set.seed(1234)
data <- usconsumption[, 1]

## Fit several models
fit1 <- nnetar(data)               # NNAR(21,1,11)
fit2 <- nnetar(data, p=5, size=3)  # NNAR(5,1,3)
fit3 <- nnetar(data, decay=1)      # NNAR(21,1,11) with regularization

## First model has negligible residuals due to overfit
sd(residuals(fit1), na.rm=TRUE)
## 0.001565025
sd(residuals(fit2), na.rm=TRUE)
## 0.4735268
sd(residuals(fit3), na.rm=TRUE)
## 0.3066509

## Too many sample paths can significantly increase the calculation time
system.time(forecast(fit1, h=15, PI=FALSE))
##   user  system elapsed
##   0.03    0.00    0.03
system.time(forecast(fit1, h=10, PI=TRUE, npaths=50, bootstrap=TRUE))
##   user  system elapsed
##  7.728   0.000   7.729
system.time(forecast(fit1, h=10, PI=TRUE, npaths=500, bootstrap=TRUE))
##   user  system elapsed
## 76.427   0.000  76.431

fcast1 <- forecast(fit1, h=10, PI=TRUE, npaths=150, bootstrap=TRUE)
fcast2 <- forecast(fit2, h=10, PI=TRUE, npaths=150, bootstrap=TRUE)
fcast3 <- forecast(fit3, h=10, PI=TRUE, npaths=150, bootstrap=TRUE)

par(mfrow = c(3, 1))
plot(fcast1)
plot(fcast2)
plot(fcast3)
```

[PI_comparison.pdf](https://github.com/robjhyndman/forecast/files/258349/PI_comparison.pdf)

### CODE REVIEW

**Comment by robjhyndman** [comment]
Sorry for the long delay in responding. This looks useful. 

In response to the questions:
1. Yes. Splitting nnetar and forecast.nnetar makes sense.
2. Yes.
3. Maybe 100 for now until we can speed it up.
4. As we know the true mean here to be zero, I think it is better to use mean of squared resid rather than var when estimating sigma^2.

I'll merge this when the above are addressed.

**Comment by gabrielcaceres** [comment]
RE: summing the residuals. Do we know the true mean to be zero? I thought since this was nonlinear least squares it wouldn't be guaranteed that the residuals add up to zero. 

Regarding the PR:

I believe all the points above are addressed now. 

A couple of notes:
- I included code from `forecast.nnetar` inside `simulate.nnetar` instead of calling the `forecast` method inside the function. This improved the speed by ~10x; running 1000 paths takes about 15 seconds on my laptop. 
- Related to the point above, `simulate.nnetar` in essence can also do point forecasts now. Running `simulate.nnetar( ..., innov=0,...)` should produce the same point forecasts as `forecast.nnetar` (although only the forecasts are returned, not the full `nnetar` object).
- I'll update the way innovations are handled after getting your opinion on #363. 
- As a possible way to get around the issue of tiny intervals due to overfitting, I added an `innov` argument to `forecast.nnetar` so one can provide by hand innovations to be used (which then are bootstrapped for each simulated path). I can remove this if you'd prefer.

**Comment by robjhyndman** [comment]
We know the true mean of the residuals is zero, although the sample mean will generally not be zero.

 Currently we are not using ... in forecast.nnetar(), so perhaps any additional arguments could go through to simulate.nnetar. Then you don't need an explicit innov argument in forecast.nnetar(). 

Also, please make sure any pull requests are passing the travis checks. You can see the problems at https://travis-ci.org/robjhyndman/forecast/builds/159037035

**Comment by gabrielcaceres** [comment]
Oops, apologies about the failed checks. I thought I had fixed the missing bracket in the documentation and then forgot to look at the updated checks.

Now `simulate.nnetar` should be using the correct scaled residuals, as discussed in #363.

Good point on passing the `...`. I removed the `innov` argument from `forecast.nnetar` and passed `...` to `simulate.nnetar` instead. One possible issue, is that when creating the prediction intervals we're simulating many paths and would want to use different innovations each time. 

One possibility is to add something like:

```
  else if(length(innov) > nsim)
    e <- sample(innov, nsim, replace=TRUE)
```

to the following part of `simulate.nnetar`:

```
if(bootstrap)
  {
    res <- rowMeans(sapply(object$model, residuals))
    res <- na.omit(res)
    res <- res - mean(res)          #center residuals
    e <- sample(res,nsim,replace=TRUE)
  }
  else if(is.null(innov))
    res <- rowMeans(sapply(object$model, residuals))
    e <- rnorm(nsim, 0, sd(res, na.rm=TRUE))
  else if(length(innov)==nsim)
    e <- innov
  else if(length(innov)==1)
    e <- rep(innov, nsim)
  else
    stop("Length of innov must be equal to nsim")
}
```
￼

**Comment by robjhyndman** [comment]
Good point. I didn't think that through. Sorry about that.

I think it might be better to go back to your original suggestion of having an innov argument in forecast.nnetar(). The problem with sampling is that you have less control over what innovations actually get used. For example, you might want to have autocorrelated residuals, or residuals with changing variance. So we need to retain control over exactly what gets used in each simulation.

**Comment by gabrielcaceres** [comment]
Hmm interesting, I hadn't thought about that. The original reason I put in an `innov` argument was simply to have a workaround in case the residuals were too small to give useful intervals, but I can see the value in having control over the innovations. Do you think then that might also be a useful addition to the other `forecast.XXX` methods? (not necessarily for this PR, but wondering in general).

**Comment by robjhyndman** [comment]
Yes. I thought that once it was introduced into forecast.nnetar, we should do something similar in other forecast functions that allow simulations.

**Comment by gabrielcaceres** [comment]
OK, I believe this should work now. See how you feel about the speed, maybe `npaths` should be reduced a bit, not sure what's the best number.

**Pull request merged**
