### PR TITLE
Resolve namespace issue with ggplot 2.3.0

### PR DESCRIPTION
**Pull request by mitchelloharawild**
Thanks @hadley

### CODE REVIEW

**Comment by mitchelloharawild** [comment]
Further testing indicates that this doesn't work.
As far as I can tell, our S3 methods are being registered to forecast::autolayer, and are not accessible to ggplot2::autolayer. Any thoughts?

**Comment by mitchelloharawild** [comment]
I've also played around with something similar to this before, but I recall having some other problems with it (conditional imports need to be fairly simple and some orders of installation caused issues?). I'll need to set up an MRE for it and play around with it some more.

**Comment by hadley** [comment]
It may be that we can't decouple forecast and ggplot2 versions, but it would be nice to spend a little time on it, because this problem crops up every now and then, and it would be good to have a solution. 

I've been thinking we need to start capturing tricks for making your package work with multiple other versions of a package. The basics aren't too hard, but you need to think a little about where you define things, and it gets complicated fast if a generic has moved packages.

@lionel- might also have other ideas for how to tackle this

**Comment by mitchelloharawild** [comment]
Here's a repo reproducing the situation:
https://github.com/mitchelloharawild/SharedGeneric

**Comment by mitchelloharawild** [comment]
The repo is now up to the closest I've gotten it to working.
To break it: install CRAN ggplot2, install SharedGeneric, install dev ggplot2.

**Comment by lionel-** [comment]
I think the issue is at https://github.com/mitchelloharawild/SharedGeneric/blob/806368c55234f3569a8f04841aad2fb3f7683d47/R/generic.R#L5

You may need to pass the ggplot2 namespace as `envir` argument of `registerS3method()`:

```
.onLoad <- function(...) {
  ns <- getNamespace("ggplot2")
  if (exists("autolayer", ns)) {
    registerS3method("autolayer", "ts", "autolayer.ts", ns)
  }
}
```

Otherwise it will find the `autolayer()` closure in your namespace and register there (there is no check as to the content of the closure).

**Comment by mitchelloharawild** [comment]
With those changes and dev version of ggplot2:

```r

> library(SharedGeneric)
Warning message:
S3 method ‘autolayer.ts’ was declared but not found 
> library(ggplot2)

Attaching package: ‘ggplot2’

The following object is masked from ‘package:SharedGeneric’:

    autolayer

> ggplot() + autolayer(USAccDeaths)
Error: Objects of type ts not supported by autolayer.
```

**Comment by lionel-** [comment]
oh hmm... Could you please try with the `register_s3_method()` function defined in https://github.com/hadley/dtplyr/blob/master/R/compat-dplyr-0.6.0.R

**Comment by mitchelloharawild** [comment]
That seems to fix the method registration, because it now registers to forecast::autolayer and then .onLoad will additionally register it to ggplot2::autolayer.

There can be a few issues still (if ggplot2 is updated while forecast is loaded), although this just requires a restart of R.

Should we fix the autolayer masking message or leave it?

**Comment by hadley** [comment]
I think you have to fix the masking message (otherwise that turns into an R CMD check issue)

**Comment by hadley** [comment]
Oh hmmm, the `.onLoad` hack should fix that.

**Comment by hadley** [comment]
@mitchelloharawild do you have a pr that incorporates both techniques?

**Comment by mitchelloharawild** [comment]
I'm not sure what you mean by both techniques, but I've made a PR with the changes from the SharedGeneric repo. Did you want to compare the attempts that we've made?

**Comment by hadley** [comment]
In https://github.com/mitchelloharawild/SharedGeneric/blob/master/R/generic.R#L45, you also need to do `autolayer <<- ns$autolayer`

**Comment by mitchelloharawild** [comment]
Ah, that makes more sense for how the masking doesn't occur. Thanks!

**Pull request closed without merging**
