### PR TITLE
Added support for conditional mean forecast w/ BoxCox transforms (#17)

### PR DESCRIPTION
**Pull request by mitchelloharawild**
http://robjhyndman.com/hyndsight/backtransforming/

### CODE REVIEW

**Comment by robjhyndman** [comment]
Units tests failing. Also, why use forecast:::function in arfima and forecast.fracdiff?

**Comment by mitchelloharawild** [comment]
That was a package localisation issue I had before, there's no need for them. I'll fix that now. (Was wanting a travis check because I suspected some issues...)

**Comment by mitchelloharawild** [comment]
Don't merge yet, would like to do more tests.

**Comment by mitchelloharawild** [comment]
Don't merge yet, would like to do more tests.

**Comment by mitchelloharawild** [comment]
Hey Rob,

For multivariate responses, should the variance be done column-wise? Or do we need to expand interactions in the Taylor expansion?

**Comment by robjhyndman** [comment]
Good question. I think just do it columnwise in the first instance. In other words, ignore the covariance terms.

**Comment by mitchelloharawild** [comment]
Ready for merging.

**Comment by mitchelloharawild** [comment]
@robjhyndman 
Ready for merge

**Pull request merged**
