### PR TITLE
Modify nnetar to allow xreg (plus other small tweaks)

### PR DESCRIPTION
**Pull request by gabrielcaceres**
I modified nnetar to allow external regressors and passing additional arguments to nnet. A couple other small tweaks as well. 

The main motivation for allowing passing arguments to nnet, is that I've seen significant improvements in performance (and stability!) when tweaking the default parameters, particularly 'decay' (i.e. regularization) which otherwise defaults to 0. Also, if a large number of lags/external regressors are used, one might hit the limit of maximum number of weights which can easily be changed through 'MaxNWts'.

Also added some unit tests if you think that'd be useful to include (not sure why there's an extra space next to the 'oilnet' test... it doesn't show up in my local copy).

I can try to clean up the history first if it looks a bit messy; I also noticed some typos in the commit comments I wrote (just getting started with git and need to figure out how to edit them).

A few limitation on how I've implemented it *so far*:
- xreg must be numeric
- xreg cannot have any NAs
- xreg is not scaled before being passed to nnet

In addition to trying to address the points above, I also have these in my personal to-do list to improve:
- Update documentation with changes made
- Need to address possible NAs at the end of time series (i.e. needed as lags for forecasting); currently I believe it should just result in an error from nnet
- nnet recycles values if input too short (and cut cuts it off if too long), so needs a warning/fix if xreg is included/excluded erroneously (currenly gives possibly wrong output without any signs of error!)
- Maybe more tests

Maybe you'd prefer if some of these are addressed before considering merging it?
Any other issues I may have missed?

### CODE REVIEW

**Comment by robjhyndman** [comment]
Please update documentation and add a check for input length. Other items can wait.

**Comment by gabrielcaceres** [comment]
OK, will do!
By "check input length" do you mean check that the length of the series and xreg match in 'nnetar' prior to fitting? Or related to my point of nnet recycling values when predicting, and thus adding a check for xreg inside of 'forecast.nnetar'? (or possibly both) 

Actually, I just realized that in the "nnet recycles/drops input" comment above, I didn't clarify that refers specifically when using 'predict.nnet' and thus affects the forecast only, not the fitting. Currently, if the time-series and xreg don't match in size then there should be the standard error when trying to cbind them inside of 'nnetar' (I can add a more explicit check & error, of course).

**Comment by robjhyndman** [comment]
I was referring to the recycling issue. But it wouldn't hurt to add such length checks wherever there might be a problem.

**Comment by robjhyndman** [comment]
```
##
## Test script for nnetar mods comparing models with & without external regressors
## Currently only tested on usconsumption data
##
library(forecast)
library(fpp)
##
## Path to new nnetar() function
source("/home/gcaceres/Documents/Projects/R_packages/forecast/R/nnetar.R")

## Set up validation data
ntrain <- 120
ntest <- 164-ntrain
ts_train <- ts(usconsumption[1:ntrain,1])
ts_test <- ts(usconsumption[(ntrain+1):164,1])
xtrain <- usconsumption[1:ntrain,2]
xtest <- usconsumption[(ntrain+1):164,2]

## ARIMA(1,0,2) model from https://www.otexts.org/fpp/9/1
##
ar_fit <- Arima(ts_train, order=c(1,0,2))
arxreg_fit <- Arima(ts_train, xreg=xtrain, order=c(1,0,2))
par(mfcol=c(2, 1))
ar_fcast <- forecast(ar_fit, h=ntest)
plot(ar_fcast,
     main="Forecasts from ARIMA")
lines((length(ts_train)+1):164, ts_test)
##
arxreg_fcast <- forecast(arxreg_fit,xreg=xtest, h=ntest)
plot(arxreg_fcast,
     main="Forecasts from regression with ARIMA(1,0,2) errors")
lines((length(ts_train)+1):164, ts_test)
mean((as.numeric(ar_fcast$mean) - ts_test)^2)
mean((as.numeric(arxreg_fcast$mean) - ts_test)^2)

## ARIMA(2,0,0) model
##
ar_fit <- Arima(ts_train, order=c(2,0,0))
arxreg_fit <- Arima(ts_train, xreg=xtrain, order=c(2,0,0))
par(mfcol=c(2, 1))
ar_fcast <- forecast(ar_fit, h=ntest)
plot(ar_fcast,
     main="Forecasts from ARIMA")
lines((length(ts_train)+1):164, ts_test)
##
arxreg_fcast <- forecast(arxreg_fit,xreg=xtest, h=ntest)
plot(arxreg_fcast,
     main="Forecasts from regression with ARIMA(1,0,2) errors")
lines((length(ts_train)+1):164, ts_test)
mean((as.numeric(ar_fcast$mean) - ts_test)^2)
mean((as.numeric(arxreg_fcast$mean) - ts_test)^2)

## Default nnet parameters (pretty unstable!)
##
nn_fit <- nnetar(ts_train, p=2)
nnxreg_fit <- nnetar(ts_train, p=2, xreg=xtrain)
par(mfcol=c(2, 1))
nn_fcast <- forecast(nn_fit, h=ntest)
plot(ts_train, xlim=c(0, 165), main="Forecasts from nnetar")
lines(nn_fcast$mean, col="blue")
lines((length(ts_train)+1):164, ts_test)
##
nnxreg_fcast <- forecast(nnxreg_fit,xreg=xtest, h=ntest)
plot(ts_train, xlim=c(0, 165), main="Forecasts from nnetar")
lines(nnxreg_fcast$mean,col="blue")
lines((length(ts_train)+1):164, ts_test)
mean((as.numeric(nn_fcast$mean) - ts_test)^2)
mean((as.numeric(nnxreg_fcast$mean) - ts_test)^2)

## Tweaked nnet parameters, much better!
nn_p <- 2
nn_size <- 2
nn_decay <- 0.1
nn_maxit <- 100
nn_fit <- nnetar(ts_train, p=nn_p, size=nn_size, decay=nn_decay, maxit=nn_maxit, center=T, scale=T)
nnxreg_fit <- nnetar(ts_train, p=nn_p, xreg=xtrain, size=nn_size, decay=nn_decay, maxit=nn_maxit, center=T, scale=T)
par(mfcol=c(2, 1))
nn_fcast <- forecast(nn_fit, h=ntest)
plot(ts_train, xlim=c(0, 165), main="Forecasts from nnetar")
lines(nn_fcast$mean, col="blue")
lines((length(ts_train)+1):164, ts_test)
##
nnxreg_fcast <- forecast(nnxreg_fit,xreg=xtest, h=ntest)
plot(ts_train, xlim=c(0, 165), main="Forecasts from nnetar")
lines(nnxreg_fcast$mean,col="blue")
lines((length(ts_train)+1):164, ts_test)
mean((as.numeric(nn_fcast$mean) - ts_test)^2)
mean((as.numeric(nnxreg_fcast$mean) - ts_test)^2)

## Increased number of lags
nn_p <- 8
nn_size <- 8
nn_decay <- 0.1
nn_maxit <- 100
nn_fit <- nnetar(ts_train, p=nn_p, size=nn_size, decay=nn_decay, maxit=nn_maxit, center=T, scale=T)
nnxreg_fit <- nnetar(ts_train, p=nn_p, xreg=xtrain, size=nn_size, decay=nn_decay, maxit=nn_maxit, center=T, scale=T)
par(mfcol=c(2, 1))
nn_fcast <- forecast(nn_fit, h=ntest)
plot(ts_train, xlim=c(0, 165), main="Forecasts from nnetar")
lines(nn_fcast$mean, col="blue")
lines((length(ts_train)+1):164, ts_test)
##
nnxreg_fcast <- forecast(nnxreg_fit,xreg=xtest, h=ntest)
plot(ts_train, xlim=c(0, 165), main="Forecasts from nnetar")
lines(nnxreg_fcast$mean,col="blue")
lines((length(ts_train)+1):164, ts_test)
mean((as.numeric(nn_fcast$mean) - ts_test)^2)
mean((as.numeric(nnxreg_fcast$mean) - ts_test)^2)
```

**Pull request merged**
