### PR TITLE
Standardize inputs in 'nnetar'

### PR DESCRIPTION
**Pull request by gabrielcaceres**
As a follow up from #235, I added code to standardize the neural net inputs (both the series and xreg). 
There's an optional argument to disable this if one prefers (e.g. if scaled differently beforehand, or if no scaling is desired). 

It should be fairly straightforward to generalize to include the option of user-defined centering and scaling to pass to [`scale`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/scale.html), if that seems better in the future.

As a side question, do you have a preference regarding coding style? (e.g. curly brackets on their own line, number of spaces to indent, etc)
In my first pull request I tried to reproduce the style of the rest of nnetar.R, but looking through other scripts I've seen slightly different styles.

I just left these new bits of code like what I normally use (and how I have my editor set up), but can clean it up according to what you prefer.

### CODE REVIEW

**Comment by robjhyndman** [comment]
You need to undo the scaling before undoing the Box-Cox transformation -- the reverse from how they were originally applied.

Please test on the following code:
```
library(magrittr)
lynx %>% nnetar(lambda=0.5,scale=TRUE) %>% forecast %>% plot
lynx %>% nnetar(scale=TRUE) %>% forecast %>% plot
lynx %>% nnetar(lambda=0.5,scale=FALSE) %>% forecast %>% plot
lynx %>% nnetar(scale=FALSE) %>% forecast %>% plot
```

My preferred coding style is 2 space indents, and braces on their own lines. But the code is not consistent due to various people writing patches and submitting pull requests following their own preferences. I haven't attempted to impose consistency.

**Comment by gabrielcaceres** [comment]
Maybe I'm missing something, but I do believe it's doing Box-Cox -> Scaling -> Undo Scaling -> Inverse Box-Cox in both nnetar and forecast.nnetar.

Piping it like in the example you suggest gives an error because there's no plot method for a nnetar forecast, and it seems to be looking for an upper and lower interval like given by an Arima forecast.

Breaking down the command and plotting `fit$mean` looks fine to me though. Is there something I'm overlooking?

**Comment by robjhyndman** [comment]
Sorry, I misread the code.

there is a forecast method for nnetar which returns a forecast object. It should plot ok, and does for me.

**Comment by gabrielcaceres** [comment]
Oops, you're right, it does plot ok. The issue with `max(x$upper)` was just a warning, not an error... too many windows open and I missed the actual plot and just saw the output on the command line.

**Comment by gabrielcaceres** [comment]
By the way, didn't think this was worth opening up a question/issue on it's own, but I wanted to ask if you thought it might be more useful to provide a default `decay` argument (i.e. regularization). 

The default in `nnet` is `decay=0` but as you might have noticed in the plot examples you suggested earlier, the results can vary wildly between iterations (even with averaging over multiple runs). Adding the regularization term does produce more reasonable results and in a much more consistent manner, but the downsize is that I'm not sure what a "good" default value would be (and it probably would/should vary between problems and network size). From what I've seen, 1 often seems reasonable enough and can be tweaked from there, but I'm not sure. 

One of the main advantages I could see of having it listed explicitly is making it clearer that it's a useful parameter to tweak. Maybe it could be included directly in the call to nnetar but just have the same default as `nnet` (i.e. 0)? Although having a non-zero default might give better results "out of the box".

To better see what I mean, you can try running both of these several times
```
lynx %>% nnetar(lambda=0.5,scale=TRUE, decay=0) %>% forecast %>% plot
lynx %>% nnetar(lambda=0.5,scale=TRUE, decay=1) %>% forecast %>% plot
```
coincidentally, a value of 1 does give quite a similar result to the auto.arima forecast in this case
```
lynx %>% auto.arima(lambda=0.5) %>% forecast %>% plot
```

**Comment by robjhyndman** [comment]
I'd rather leave it as it is unless you or someone else can produce evidence to support a default other than 0 for these types of models when applied to a large range of time series data.

**Comment by gabrielcaceres** [comment]
Ok sounds good, I'll just leave it as is then.

**Pull request merged**
