### PR TITLE
Added h-step fitted values

### PR DESCRIPTION
**Pull request by mitchelloharawild**

### CODE REVIEW

**Comment by robjhyndman** [comment]
OK, but I don't think hfitted needs to be user-visible. Users can just use fitted() with argument h.

**Comment by mitchelloharawild** [comment]
Good point. I was planning to do that, and create fitted.class help files. I'll fix that up now.

**Comment by gabrielcaceres** [comment]
Haven't had a chance to test it yet, but I believe `hfitted` might break when `xreg` is used (for the functions that can use it).

**Comment by gabrielcaceres** [comment]
Also, a couple suggestions: 

- You might want to warn in the documentation that the h-step fitted values actually need to be *calculated* instead of just pulled from the fit, since it can be more time consuming.
- Maybe after running `fitted` with `h>1` the values can be stored in the original object (possibly optionally if memory is more limited than CPU time) and then simply retrieved in subsequent calls (although not sure if this can be done as a side effect rather or if it'd be necessary to return a new copy of the full object).
- Perhaps there could be a flag for "up to h" since all the intermediate values are calculated anyway, and if one is interested in them might as well save them instead of repeating the calculation...

**Pull request merged**
