### PR TITLE
geom_forecast() overhaul

### PR DESCRIPTION
**Pull request by mitchelloharawild**
- mforecast support
- rewritten Geom structure
- Added support for forecasts of length 1 (and 0)
- Custom geom_forecast() draw_key
- Far more structurally robust
- Clearer code
- Removed aesthetic warnings

Code sample:
```
ldeaths <- cbind(mdeaths, fdeaths)
autoplot(USAccDeaths) + geom_forecast()
autoplot(ldeaths) + geom_forecast()

fit <- tslm(ldeaths ~ trend + season)
mfcast <- forecast(fit, h=24)
ggplot() + geom_forecast(mfcast)
ggplot() + geom_forecast(mfcast, series = TRUE) # Anything without a name for each series will find the series name
ggplot() + geom_forecast(mfcast, series = c("Male deaths", "Female deaths")) # But it can be set manually if it doesn't work

# When the forecast length is one, the graph will now work (using point and linerange, not line and ribbon)
autoplot(ldeaths) + geom_forecast(h=1)
```

### CODE REVIEW

**Comment by robjhyndman** [comment]
```R
> autoplot(WWWusage) + geom_forecast(snaive(WWWusage), plot.conf=FALSE)
Error: geom_forecast requires the following missing aesthetics: ymin, ymax, level
```

**Comment by robjhyndman** [comment]
How about we change the argument `plot.conf` to `PI`? It is simpler.

**Comment by mitchelloharawild** [comment]
plot.conf is for consistency with plot.forecast()

Happy to change all of the plot.conf arguments to be PI though.

**Comment by robjhyndman** [comment]
Yes, let's do that.

**Pull request merged**
